=== HugoZHL/MiniBBS/static/xml/postprofile.dtd
<!ELEMENT Post (No, PostUser, Block, Title, Content, PostTime, Clicks, ReplyNum, Replies)>
        <!ELEMENT Replies (Reply*)>
        <!ELEMENT Reply (Floor, OriginalNo, ReplyUser, ReplyContent, ReplyTime, PraiseNum)>
        <!ELEMENT No (#PCDATA)>
        <!ELEMENT PostUser (#PCDATA)>
        <!ELEMENT Block (#PCDATA)>
        <!ELEMENT PostTime (#PCDATA)>
        <!ELEMENT Title (#PCDATA)>
        <!ELEMENT Content (#PCDATA)>
        <!ELEMENT Clicks (#PCDATA)>
        <!ELEMENT ReplyNum (#PCDATA)>
        <!ELEMENT Floor (#PCDATA)>
        <!ELEMENT OriginalNo (#PCDATA)>
        <!ELEMENT ReplyUser (#PCDATA)>
        <!ELEMENT ReplyContent (#PCDATA)>
        <!ELEMENT ReplyTime (#PCDATA)>
        <!ELEMENT PraiseNum (#PCDATA)>

=== HugoZHL/MiniBBS/static/xml/post_301.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Post
  SYSTEM 'postprofile.dtd'>
	<Post>
		<No>301</No>
		<PostUser>User0</PostUser>
		<Title>Hello world!!!</Title>
		<Content>I am really new here. Lets start chatting!</Content>
		<PostTime>2018-12-30 01:59:33</PostTime>
		<Clicks>4</Clicks>
		<ReplyNum>0</ReplyNum>
		<Replies/>
	</Post>

=== HugoZHL/MiniBBS/static/xml/post_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Post
  SYSTEM 'postprofile.dtd'>
	<Post>
		<No>3</No>
		<PostUser>User0</PostUser>
		<Block>Job</Block>
		<Title>Looking for jobs.</Title>
		<Content>I am looking for jobs.</Content>
		<PostTime>2018-12-29 19:35:58</PostTime>
		<Clicks>3</Clicks>
		<ReplyNum>11</ReplyNum>
		<Replies>
			<Reply>
				<Floor>1</Floor>
				<OriginalNo>11</OriginalNo>
				<ReplyUser>HugoZ</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:15</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>2</Floor>
				<OriginalNo>12</OriginalNo>
				<ReplyUser>TPF</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:15</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>3</Floor>
				<OriginalNo>13</OriginalNo>
				<ReplyUser>WSB</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:15</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>4</Floor>
				<OriginalNo>14</OriginalNo>
				<ReplyUser>User0</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:15</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>5</Floor>
				<OriginalNo>15</OriginalNo>
				<ReplyUser>User1</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:15</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>6</Floor>
				<OriginalNo>1511</OriginalNo>
				<ReplyUser>User94</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-30 01:57:29</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>7</Floor>
				<OriginalNo>1512</OriginalNo>
				<ReplyUser>User95</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-30 01:57:29</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>8</Floor>
				<OriginalNo>1513</OriginalNo>
				<ReplyUser>User96</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-30 01:57:29</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>9</Floor>
				<OriginalNo>1514</OriginalNo>
				<ReplyUser>User97</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-30 01:57:29</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>10</Floor>
				<OriginalNo>1515</OriginalNo>
				<ReplyUser>User98</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-30 01:57:29</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>11</Floor>
				<OriginalNo>1749</OriginalNo>
				<ReplyUser>HugoZ</ReplyUser>
				<ReplyContent>I'm also looking for a job.</ReplyContent>
				<ReplyTime>2018-12-31 18:35:52</ReplyTime>
				<PraiseNum>1</PraiseNum>
			</Reply>
		</Replies>
	</Post>

=== HugoZHL/MiniBBS/static/xml/post_258.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Post
  SYSTEM 'postprofile.dtd'>
	<Post>
		<No>258</No>
		<PostUser>User85</PostUser>
		<Block>Sports</Block>
		<Title>Good game</Title>
		<Content>Peking University Sports Events are so great!</Content>
		<PostTime>2018-12-29 19:35:58</PostTime>
		<Clicks>1</Clicks>
		<ReplyNum>5</ReplyNum>
		<Replies>
			<Reply>
				<Floor>1</Floor>
				<OriginalNo>1286</OriginalNo>
				<ReplyUser>HugoZ</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:16</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>2</Floor>
				<OriginalNo>1287</OriginalNo>
				<ReplyUser>TPF</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:16</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>3</Floor>
				<OriginalNo>1288</OriginalNo>
				<ReplyUser>WSB</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:16</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>4</Floor>
				<OriginalNo>1289</OriginalNo>
				<ReplyUser>User0</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:16</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>5</Floor>
				<OriginalNo>1290</OriginalNo>
				<ReplyUser>User1</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:16</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
		</Replies>
	</Post>

=== HugoZHL/MiniBBS/static/xml/post_348.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Post
  SYSTEM 'postprofile.dtd'>
	<Post>
		<No>348</No>
		<PostUser>User0</PostUser>
		<Block>School Life</Block>
		<Title>≤‚ ‘2</Title>
		<Content>≤‚ ‘2</Content>
		<PostTime>2018-12-31 19:54:09</PostTime>
		<Clicks>1</Clicks>
		<ReplyNum>0</ReplyNum>
		<Replies/>
	</Post>

=== HugoZHL/MiniBBS/static/xml/post_342.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Post
  SYSTEM 'postprofile.dtd'>
	<Post>
		<No>342</No>
		<PostUser>Complicated</PostUser>
		<Block>School Life</Block>
		<Title>Hey man, anyone go hiking this weekend?</Title>
		<Content>Come with me and enjoy your life!</Content>
		<PostTime>2018-12-31 18:45:56</PostTime>
		<Clicks>12</Clicks>
		<ReplyNum>1</ReplyNum>
		<Replies>
			<Reply>
				<Floor>1</Floor>
				<OriginalNo>1751</OriginalNo>
				<ReplyUser>Complicated</ReplyUser>
				<ReplyContent>anyone?</ReplyContent>
				<ReplyTime>2018-12-31 18:46:30</ReplyTime>
				<PraiseNum>9</PraiseNum>
			</Reply>
		</Replies>
	</Post>

=== HugoZHL/MiniBBS/static/xml/post_259.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Post
  SYSTEM 'postprofile.dtd'>
	<Post>
		<No>259</No>
		<PostUser>User86</PostUser>
		<Block>School Life</Block>
		<Title>Hello world!</Title>
		<Content>I am new here. Lets start chatting!</Content>
		<PostTime>2018-12-29 19:35:58</PostTime>
		<Clicks>1</Clicks>
		<ReplyNum>5</ReplyNum>
		<Replies>
			<Reply>
				<Floor>1</Floor>
				<OriginalNo>1291</OriginalNo>
				<ReplyUser>HugoZ</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:16</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>2</Floor>
				<OriginalNo>1292</OriginalNo>
				<ReplyUser>TPF</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:16</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>3</Floor>
				<OriginalNo>1293</OriginalNo>
				<ReplyUser>WSB</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:16</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>4</Floor>
				<OriginalNo>1294</OriginalNo>
				<ReplyUser>User0</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:16</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
			<Reply>
				<Floor>5</Floor>
				<OriginalNo>1295</OriginalNo>
				<ReplyUser>User1</ReplyUser>
				<ReplyContent>Good Post!</ReplyContent>
				<ReplyTime>2018-12-29 21:25:16</ReplyTime>
				<PraiseNum>0</PraiseNum>
			</Reply>
		</Replies>
	</Post>

=== HugoZHL/MiniBBS/static/xml/post_347.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Post
  SYSTEM 'postprofile.dtd'>
	<Post>
		<No>347</No>
		<PostUser>User0</PostUser>
		<Block>School Life</Block>
		<Title>▓Р╩н </Title>
		<Content>▓Р╩нол╬─</Content>
		<PostTime>2018-12-31 19:46:35</PostTime>
		<Clicks>2</Clicks>
		<ReplyNum>0</ReplyNum>
		<Replies/>
	</Post>

=== HugoZHL/MiniBBS/static/xml/post_345.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Post
  SYSTEM 'postprofile.dtd'>
	<Post>
		<No>345</No>
		<PostUser>Complicated</PostUser>
		<Block>School Life</Block>
		<Title>有哪些有趣的讲座呀？</Title>
		<Content>求问~</Content>
		<PostTime>2018-12-31 18:54:32</PostTime>
		<Clicks>7</Clicks>
		<ReplyNum>2</ReplyNum>
		<Replies>
			<Reply>
				<Floor>1</Floor>
				<OriginalNo>1753</OriginalNo>
				<ReplyUser>HugoZ</ReplyUser>
				<ReplyContent>有很多哦</ReplyContent>
				<ReplyTime>2019-01-01 00:52:50</ReplyTime>
				<PraiseNum>1</PraiseNum>
			</Reply>
			<Reply>
				<Floor>2</Floor>
				<OriginalNo>1754</OriginalNo>
				<ReplyUser>HugoZ</ReplyUser>
				<ReplyContent>可以上公众号查找的</ReplyContent>
				<ReplyTime>2019-01-01 00:52:55</ReplyTime>
				<PraiseNum>3</PraiseNum>
			</Reply>
		</Replies>
	</Post>
