=== HugoZHL/MiniBBS/static/xml/secprofile.dtd
<!ELEMENT Section (Info, Posts)>
        <!ELEMENT Info (SecId, SecName, Master, PostNum, Description)>
        <!ELEMENT Posts (Post*)>
        <!ELEMENT Post (No, PostUser, Title, Content, PostTime, Clicks, Replies)>
        <!ELEMENT Replies (Reply*)>
        <!ELEMENT Reply (Floor, ReplyUser, ReplyContent, ReplyTime, PraiseNum)>
        <!ELEMENT SecId (#PCDATA)>
        <!ELEMENT SecName (#PCDATA)>
        <!ELEMENT Master (#PCDATA)>
        <!ELEMENT PostNum (#PCDATA)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT No (#PCDATA)>
        <!ELEMENT Block (#PCDATA)>
        <!ELEMENT PostUser (#PCDATA)>
        <!ELEMENT Title (#PCDATA)>
        <!ELEMENT Content (#PCDATA)>
        <!ELEMENT PostTime (#PCDATA)>
        <!ELEMENT Clicks (#PCDATA)>
        <!ELEMENT Floor (#PCDATA)>
        <!ELEMENT ReplyUser (#PCDATA)>
        <!ELEMENT ReplyContent (#PCDATA)>
        <!ELEMENT ReplyTime (#PCDATA)>
        <!ELEMENT PraiseNum (#PCDATA)>

=== HugoZHL/MiniBBS/static/xml/sec_8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Section
  SYSTEM 'secprofile.dtd'>
	<Section>
		<Info>
			<SecId>8</SecId>
			<SecName>test</SecName>
			<Master>HugoZ</Master>
			<PostNum>0</PostNum>
			<Description>testtest</Description>
		</Info>
		<Posts/>
	</Section>

=== HugoZHL/MiniBBS/static/xml/sec_7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Section
  SYSTEM 'secprofile.dtd'>
	<Section>
		<Info>
			<SecId>7</SecId>
			<SecName>test</SecName>
			<Master>HugoZ</Master>
			<PostNum>0</PostNum>
			<Description>Good</Description>
		</Info>
		<Posts/>
	</Section>
