=== HugoZHL/MiniBBS/static/xml/userprofile.dtd
<!ELEMENT User (UserName, Info)>
        <!ELEMENT Info (BasicInfo, OtherInfo)>
        <!ELEMENT BasicInfo (Gender, Age, Level, Birthday, Email)>
        <!ELEMENT OtherInfo (Posts, Replies)>
        <!ELEMENT Posts (Post*)>
        <!ELEMENT Post (No, Block, PostUser, Title, Content, PostTime, Clicks, ReplyNum)>
        <!ELEMENT Replies (Reply*)>
        <!ELEMENT Reply (Title, PostUser, PostID, OriginalNo, Floor, ReplyUser, ReplyContent, ReplyTime, PraiseNum)>
        <!ELEMENT UserName (#PCDATA)>
        <!ELEMENT Gender (#PCDATA)>
        <!ELEMENT Age (#PCDATA)>
        <!ELEMENT Level (#PCDATA)>
        <!ELEMENT Birthday (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT No (#PCDATA)>
        <!ELEMENT Block (#PCDATA)>
        <!ELEMENT PostUser (#PCDATA)>
        <!ELEMENT PostID (#PCDATA)>
        <!ELEMENT Title (#PCDATA)>
        <!ELEMENT Content (#PCDATA)>
        <!ELEMENT PostTime (#PCDATA)>
        <!ELEMENT Clicks (#PCDATA)>
        <!ELEMENT ReplyNum (#PCDATA)>
        <!ELEMENT OriginalNo (#PCDATA)>
        <!ELEMENT Floor (#PCDATA)>
        <!ELEMENT ReplyUser (#PCDATA)>
        <!ELEMENT ReplyContent (#PCDATA)>
        <!ELEMENT ReplyTime (#PCDATA)>
        <!ELEMENT PraiseNum (#PCDATA)>

=== HugoZHL/MiniBBS/static/xml/user_User44.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE User
  SYSTEM 'userprofile.dtd'>
	<User>
		<UserName>User44</UserName>
		<Info>
			<BasicInfo>
				<Gender>Male</Gender>
				<Age>20</Age>
				<Level>2</Level>
				<Birthday>1998-01-01</Birthday>
				<Email>user44@pku.edu.cn</Email>
			</BasicInfo>
			<OtherInfo>
				<Posts>
					<Post>
						<No>133</No>
						<Block>School Life</Block>
						<PostUser>User44</PostUser>
						<Title>Hello world!</Title>
						<Content>I am new here. Lets start chatting!</Content>
						<PostTime>2018-12-29 19:35:58</PostTime>
						<Clicks>0</Clicks>
						<ReplyNum>5</ReplyNum>
					</Post>
					<Post>
						<No>134</No>
						<Block>Lectures</Block>
						<PostUser>User44</PostUser>
						<Title>Good lecture!</Title>
						<Content>I want to attend this lecture~</Content>
						<PostTime>2018-12-29 19:35:58</PostTime>
						<Clicks>0</Clicks>
						<ReplyNum>5</ReplyNum>
					</Post>
					<Post>
						<No>135</No>
						<Block>Job</Block>
						<PostUser>User44</PostUser>
						<Title>Looking for jobs.</Title>
						<Content>I am looking for jobs.</Content>
						<PostTime>2018-12-29 19:35:58</PostTime>
						<Clicks>0</Clicks>
						<ReplyNum>5</ReplyNum>
					</Post>
				</Posts>
				<Replies/>
			</OtherInfo>
		</Info>
	</User>

=== HugoZHL/MiniBBS/static/xml/user_Complicated.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE User
  SYSTEM 'userprofile.dtd'>
	<User>
		<UserName>Complicated</UserName>
		<Info>
			<BasicInfo>
				<Gender>Male</Gender>
				<Age>0</Age>
				<Level>3</Level>
				<Birthday>2018-12-31</Birthday>
				<Email>no@no</Email>
			</BasicInfo>
			<OtherInfo>
				<Posts>
					<Post>
						<No>346</No>
						<Block>Lectures</Block>
						<PostUser>Complicated</PostUser>
						<Title>讲座好玩吗</Title>
						<Content>好不好玩呀</Content>
						<PostTime>2018-12-31 18:54:59</PostTime>
						<Clicks>0</Clicks>
						<ReplyNum>0</ReplyNum>
					</Post>
					<Post>
						<No>345</No>
						<Block>School Life</Block>
						<PostUser>Complicated</PostUser>
						<Title>有哪些有趣的讲座呀？</Title>
						<Content>求问~</Content>
						<PostTime>2018-12-31 18:54:32</PostTime>
						<Clicks>0</Clicks>
						<ReplyNum>0</ReplyNum>
					</Post>
					<Post>
						<No>344</No>
						<Block>School Life</Block>
						<PostUser>Complicated</PostUser>
						<Title>有哪些有趣的讲座呀？</Title>
						<Content>求问~</Content>
						<PostTime>2018-12-31 18:52:14</PostTime>
						<Clicks>0</Clicks>
						<ReplyNum>0</ReplyNum>
					</Post>
					<Post>
						<No>343</No>
						<Block>School Life</Block>
						<PostUser>Complicated</PostUser>
						<Title>可以说中文吗？</Title>
						<Content>这里可以用中文吗？

</Content>
						<PostTime>2018-12-31 18:49:15</PostTime>
						<Clicks>0</Clicks>
						<ReplyNum>0</ReplyNum>
					</Post>
					<Post>
						<No>342</No>
						<Block>School Life</Block>
						<PostUser>Complicated</PostUser>
						<Title>Hey man, anyone go hiking this weekend?</Title>
						<Content>Come with me and enjoy your life!</Content>
						<PostTime>2018-12-31 18:45:56</PostTime>
						<Clicks>12</Clicks>
						<ReplyNum>1</ReplyNum>
					</Post>
				</Posts>
				<Replies>
					<Reply>
						<Title>Good lecture!</Title>
						<PostUser>User0</PostUser>
						<PostID>2</PostID>
						<OriginalNo>1752</OriginalNo>
						<Floor>11</Floor>
						<ReplyUser>Complicated</ReplyUser>
						<ReplyContent>which one?</ReplyContent>
						<ReplyTime>2018-12-31 18:55:24</ReplyTime>
						<PraiseNum>0</PraiseNum>
					</Reply>
					<Reply>
						<Title>Hey man, anyone go hiking this weekend?</Title>
						<PostUser>Complicated</PostUser>
						<PostID>342</PostID>
						<OriginalNo>1751</OriginalNo>
						<Floor>1</Floor>
						<ReplyUser>Complicated</ReplyUser>
						<ReplyContent>anyone?</ReplyContent>
						<ReplyTime>2018-12-31 18:46:30</ReplyTime>
						<PraiseNum>9</PraiseNum>
					</Reply>
				</Replies>
			</OtherInfo>
		</Info>
	</User>
